### PR TITLE
Add test plugin to verify functionality

### PR DESCRIPTION
**Pull request by Sytm**
I have created this basic test plugin because of #184, so I could verify that AnvilGUI actually works on 1.18.1.

I have also added basic argument parsing to change the calls made on the AnvilGUI.Builder.

### CODE REVIEW

**Comment by iXanadu13** [comment]
I think I have relocated the dependency,but received error report when I used it.
`Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder`
`Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder`
Here is my pom.xml.Could you help me find what's wrong?
[pom.zip](https://github.com/WesJD/AnvilGUI/files/8598586/pom.zip)

**Comment by Sytm** [comment]
Just for your information: You just commented on a pull request. If you have problems you should create a new issue instead.

<details>
  <summary>To solve your problem this should suffice (click this)</summary>
  
  ```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>xanadu</groupId>
    <artifactId>NameCard</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>NameCard</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <!--<plugin> You had accidentally added the configuration for the maven shade plugin twice
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin> -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>net.wesjd.anvilgui</pattern>
                                    <shadedPattern>xanadu.namecard.commands.anvilgui</shadedPattern>
                                </relocation>
                            </relocations>
                            <minimizeJar>false</minimizeJar>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.13-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.5.3-SNAPSHOT</version>
            <scope>compile</scope> <!-- I also recommend explicitly adding the scope "compile" so that the Maven shade plugin knows it should go into the final JAR -->
        </dependency>
    </dependencies>
</project>
  ```
</details>
If you have additonal problems please create a new issue

**Comment by WesJD** [comment]
While this would be a nice addition, it is another point of maintenance and something that can be easily whipped up for testing when developing.

Ultimately, it would be nice to have actual unit tests in this project, so that we could have a common set of truths to work around. That's a larger goal though.
