### PR TITLE
Fix: NoSuchMethodError on 1.19.1

### LINKED ISSUE #221: NoSuchMethodError: #fB()
Hi
At the request of one person, I'm updating an ArtMap plugin that uses this API to open anvil-type inventories. An error occurs when migrating to version 1.19 and updating AnvilGui to the latest version
image
the line the server is complaining about
image
Server version
image

### PR DESCRIPTION
**Pull request by spnda**
Fixes #221.

1.19.1 is still on 1_19_R1, though the fB method of EntityPlayer has been remapped to fA, causing a NoSuchMethodException. I wrote a bit of Java reflection code to detect the correct method and have tested this to work on both 1.19 and 1.19.1 servers.

### CODE REVIEW

**Comment by joestr** [comment]
You could handle it like 1.14.4 which also was [NMS 1_14_R1](https://www.spigotmc.org/wiki/spigot-nms-and-minecraft-versions-1-10-1-15/).

For [1.14](https://github.com/WesJD/AnvilGUI/blob/master/1_14_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_14_R1.java)
For [1.14.4](https://github.com/WesJD/AnvilGUI/blob/master/1_14_4_R1/src/main/java/net/wesjd/anvilgui/version/special/AnvilContainer1_14_4_R1.java)

**Comment by spnda** [comment]
The 1.14.4 split is actually similar to this, as a method called `a` was renamed to `set`. Though I don't think using reflection on the classes hurts in any way. I personally don't like just relying on the version string to determine which methods to call. Or would you or WesJD think that it is in any way beneficial to split the implementation again and to not use reflection?

The 1.17.1 split was because the method we need to override was renamed, which is determined at compile time and cannot be changed at runtime without splitting the implementations into two classes, as seen by the 1.17.1 wrapper you linked.

**Comment by joestr** [comment]
At first, I am not in the position to determine which solution fits better here.

My point is that this has occurred in past and was handled differently and a consistent implementation would be beneficial as code complexity gets lower the more consistent its implemented.

Relying on a version string isn't that problematic here because the string is well-formed and established.

**Comment by WesJD** [comment]
Yep, I agree that the non-reflection route is better. The emphasis in this library has always been to avoid reflection as much as possible. Unfortunately, due to different Java versions of the game, we do have to use minimal reflection.

LGTM. Merging. Appreciate your help.
