### ISSUE TITLE
AnvilGUI does not work on 1.21.4

### ISSUE THREAD

**Issue by lauradevmc** [WesJD/AnvilGUI#376]
```
[14:39:59 ERROR]: Could not pass event InventoryClickEvent to MyPlugin v1.0
java.lang.NoClassDefFoundError: net/minecraft/core/HolderLookup$a
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[leaf-1.21.4.jar:1.21.4-494-de25622]
        at MyPlugin-1.0.jar/net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:53) ~[MyPlugin-1.0.jar:?]
        at MyPlugin-1.0.jar/net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[MyPlugin-1.0.jar:?]
        at MyPlugin-1.0.jar/net.wesjd.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:428) ~[MyPlugin-1.0.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.HolderLookup$a
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[leaf-1.21.4.jar:1.21.4-494-de25622]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[leaf-1.21.4.jar:1.21.4-494-de25622]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 38 more
```

i think this is an error on the [VersionMatcher class](https://github.com/WesJD/AnvilGUI/blob/1caa2c4862ea8b0712259f194e2a51b6a18d44c5/api/src/main/java/net/wesjd/anvilgui/version/VersionMatcher.java#L53)
